# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

compiler: gcc

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/astroconda'
        - CONDA_DEPENDENCIES='pytest sphinx'
        - PIP_DEPENDENCIES=''
        - PYTHON_VERSION=3.7
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - EVENT_TYPE='push pull_request'

    matrix:
        - SETUP_CMD='install'
        - SETUP_CMD='test'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # build sphinx documentation with warnings
        - os: linux
          env: SETUP_CMD='build_sphinx'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx_rtd_theme stsci_rtd_theme sphinx-automodapi'

        # PEP8 check with flake8 (only once, i.e. "os: linux")
        - os: linux
          env: MAIN_CMD='flake8 --count'
               SETUP_CMD='packagename' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES

    allow_failures:
        # PEP8 will fail for numerous reasons. Ignore it.
        - env: MAIN_CMD='flake8 --count'
               SETUP_CMD='packagename' TEST_CMD='flake8 --version'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD

deploy:
  provider: pypi
  skip_existing: true
  user: __token__
  password:
    secure: L4J67lu3xpOF0LmIohe/tb7Ph0e5SrWjIFeegsY3iW04dHzSo4HYKgbeav5RhcHQF9eHEVtSLrsq/F/Fa+AJJzRQyBIv74LabynOctGJojbKvMDiFKdM17X/hVSVXgXzE4AbvjPeB0P/4sIGDDJnrw/s+75Hsudo2BieNlGzOPosZuWzkPCpe79oRRF/AKe+iyuK7pbG2+VbQoj2vnZdDblblNfP0iaIsyu2N4sUpDEDetwUNtkaQj7Ji+54Krj0yDiIvX8ujufRqdVQUafY0N9ziKUkp79suNwCEvzFQH/bn5vzOPwhzqt8XkVlRIz2/6LvxSMDCqSd6LhY4NhCZAjflymClHOeV8+vkK4CBGYO2g/Zh9oCx2ck2OCjmfN+0njYT7kGmgvZZ+BUV9RaA7+5kBrL06qmusuBy5XRU4cgjrhQzv4OtcPTZH1kyN83rPtyk7iypzl5E9u7EzfqcFna0eTL6YFwTPrxQ9vx73vAvaN0qTL6VG5CJ2mzj7SQihkRLl1B3AVj9d+k3JOgsqKIBQ61yxRQEMgMdw43LaFQvjx/eAhIAonTy04/izibNNxjRde+cj9HCfVKTlG0j/W1gsV0/L+l95uT07xMZRhhvAhm6aIlmdD/mWeekNfpOGcxR2EhKv8aexUCL1gA6WKc6TSx7Un2HP8vHZlGl7k=
  on:
    branch: master
    tags: false
